# Generated by Django 3.2.21 on 2023-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Courses for schools/education', 'Courses for schools/education'), ('Pricing Inquiry', 'Pricing Inquiry'), ('Business Inquiry', 'Business Inquiry'), ('Trouble using the site', 'Trouble using the site'), ('Trouble accessing my course', 'Trouble accessing my course'), ('Recover my account', 'Recover my account'), ('Other', 'Other')], max_length=254),
        ),
    ]
