# Generated by Django 3.2.21 on 2023-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
