# Generated by Django 3.2.21 on 2023-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='level_display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=254, null=True),
        ),
    ]
