# Generated by Django 3.2.21 on 2023-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231027_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, choices=[('1-Beginner', '1-Beginnner'), ('2-Intermediate', '2-Intermediate'), ('3-Advanced', '3-Advanced')], max_length=254, null=True),
        ),
    ]
