# Generated by Django 3.2.21 on 2023-11-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
